# 3-VAZIFA

In [1]:
import pandas as pd

#### 3.1 WORLD POPULATION table ni saytdan olib quyidagi kod orqali ya'ni .read_csv() orqali csv faylini ochdim.

In [2]:
df = pd.read_csv("world_population.csv")
df

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20

#### 3.2 Quyidagi kodda .head() metodi orqali boshidagi 5ta qatorini ko'rish uchun ishlatdim. Bu ma'lumotlar to'plamini boshlang'ich qismiga tezda nazar tashlash uchun juda foydali.

In [3]:
df.head()

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00

#### 3.3 Quyidagi kodda .median() metodidan foydalandim bu metod DataFrame obyektidagi "World Population Percentage" ustunini medianini hisoblab berdi. World Population Percentagening mediani 0.07ga teng ekan.

In [4]:
df["World Population Percentage"].median()

0.07

#### 3.4 Quyidagi kodda asia o'zgaruvchisiga "Continent" columdagi qiymatlardan faqat "Asia"ga teng bo'lganlarini filtrlab oldim.

In [5]:
asia = df["Continent"]=="Asia"
asia = df[asia]
asia

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
9,140,ARM,Armenia,Yerevan,Asia,2780469,2805608,2878595,2946293,3168523,3556539,3135123,2534377,29743,93.4831,0.9962,0.03
13,91,AZE,Azerbaijan,Baku,Asia,10358074,10284951,9863480,9237202,8190337,7427836,6383060,5425317,86600,119.6082,1.0044,0.13
15,154,BHR,Bahrain,Manama,Asia,1472233,1477469,1362142,1213645,711442,517418,362595,222555,765,1924.4876,1.0061,0.02
16,8,BGD,Bangladesh,Dhaka,Asia,171186372,167420951,157830000,148391139,129193327,107147651,83929765,67541860,147570,1160.0350,1.0108,2.15
23,165,BTN,Bhutan,Thimphu,Asia,782455,772506,743274,705516,587207,558442,415257,298894,38394,20.3796,1.0064,0.01
29,175,BRN,Brunei,Bandar Seri Begawan,Asia,449002,441725,421437,396053,333926,261928,187921,133343,5765,77.8841,1.0081,0.01
33,73,KHM,Cambodia,Phnom Penh,Asia,16767842,16396860,15417523,14363532,12118841,8910808,6198959,6708525,181035,92.6221,1.0108,0.21
41,1,CHN,China,Beijing,Asia,1425887337,1424929781,1393715448,1348191368,1264099069,1153704252,982372466,822534450,9706961,146.8933,1.0000,17.88
73,131,GEO,Georgia,Tbilisi,Asia,3744385,3765912,3771132,3836831,4265172,5391636,5145843,4800426,69700,53.7214,0.9964,0.05
89,104,HKG,Hong Kong,Hong Kong,Asia,7488865,7500958,7399838,7132438,6731195,5838574,4978544,3955072,1104,6783.3922,0.9992,0.09
92,2,IND,India,New Delhi,Asia,1417173173,1396387127,1322866505,1240613620,1059633675,870452165,696828385,557501301,3287590,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,275501339,271857970,259091970,244016173,214072421,182159874,148177096,115228394,1904569,144.6529,1.0064,3.45
94,17,IRN,Iran,Tehran,Asia,88550570,87290193,81790841,75373855,65544383,55793629,38520664,28449705,1648195,53.7258,1.0071,1.11
95,35,IRQ,Iraq,Baghdad,Asia,44496122,42556984,37757813,31264875,24628858,17658381,13653369,9811347,438317,101.5158,1.0221,0.56
98,98,ISR,Israel,Jerusalem,Asia,9038309,8757489,8007778,7328445,6116958,4803254,3744608,2907307,20770,435.1617,1.0155,0.11
102,11,JPN,Japan,Tokyo,Asia,123951692,125244761,127250933,128105431,126803861,123686321,117624196,105416839,377930,327.9753,0.9947,1.55
104,83,JOR,Jordan,Amman,Asia,11285869,10928721,9494246,6931258,5056174,3480587,2216903,1557374,89342,126.3221,1.0123,0.14
105,66,KAZ,Kazakhstan,Nursultan,Asia,19397998,18979243,17835909,16627837,15236253,16866563,14172710,12265305,2724900,7.1188,1.0105,0.24
108,129,KWT,Kuwait,Kuwait City,Asia,4268873,4360444,3908743,2943356,1934901,1674938,1493870,802786,17818,239.5821,1.0044,0.05
109,110,KGZ,Kyrgyzstan,Bishkek,Asia,6630623,6424874,5914980,5483774,4935182,4394734,3691209,3016384,199951,33.1612,1.0158,0.08
110,103,LAO,Laos,Vientiane,Asia,7529475,7319399,6787419,6323418,5430853,4314443,3297519,2675283,236800,31.7968,1.0141,0.09
112,119,LBN,Lebanon,Beirut,Asia,5489739,5662923,6398940,4995800,4320642,3593700,2963702,2381791,10452,525.2334,0.9816,0.07
119,167,MAC,Macau,Concelho de Macau,Asia,695168,676283,615239,557297,431896,350227,245332,247284,30,23172.2667,1.0125,0.01
122,45,MYS,Malaysia,Kuala Lumpur,Asia,33938221,33199993,31068833,28717731,22945150,17517054,13215707,10306508,330803,102.5934,1.0109,0.43
123,174,MDV,Maldives,Malé,Asia,523787,514438,435582,361575,282507,224957,164887,123243,300,1745.9567,1.0045,0.01
135,134,MNG,Mongolia,Ulaanbaatar,Asia,3398366,3294335,2964749,2702520,2450979,2161433,1697780,1293880,1564110,2.1727,1.0151,0.04
140,26,MMR,Myanmar,Nay Pyi Taw,Asia,54179306,53423198,51483949,49390988,45538332,40099553,33465781,27284112,676578,80.0784,1.0071,0.68
143,49,NPL,Nepal,Kathmandu,Asia,30547580,29348627,27610325,27161567,24559500,19616530,15600442,12501285,147181,207.5511,1.0171,0.38
151,56,PRK,North Korea,Pyongyang,Asia,26069416,25867467,25258015,24686435,23367059,20799523,17973650,14996879,120538,216.2755,1.0038,0.33
155,127,OMN,Oman,Muscat,Asia,4576298,4543399,4191776,2881914,2344253,1804524,1017462,670693,309500,14.7861,1.0123,0.06
156,5,PAK,Pakistan,Islamabad,Asia,235824862,227196741,210969298,194454498,154369924,115414069,80624057,59290872,881912,267.4018,1.0191,2.96
158,122,PSE,Palestine,Ramallah,Asia,5250072,5019401,4484614,3992278,3139954,2124609,1453620,1118241,6220,844.0630,1.0227,0.07
163,13,PHL,Philippines,Manila,Asia,115559009,112190977,103031365,94636700,77958223,61558898,48419546,37435586,342353,337.5434,1.0147,1.45
167,143,QAT,Qatar,Doha,Asia,2695122,2760385,2414573,1713504,645937,441675,277450,118007,11586,232.6189,1.0026,0.03
182,41,SAU,Saudi Arabia,Riyadh,Asia,36408820,35997107,32749848,29411929,21547390,16004763,10171710,6106191,2149690,16.9368,1.0128,0.46
187,113,SGP,Singapore,Singapore,Asia,5975689,5909869,5650018,5163590,4053602,3022209,2400729,2061831,710,8416.4634,1.0058,0.07
194,29,KOR,South Korea,Seoul,Asia,51815810,51844690,50994401,48813042,46788591,44120039,38170501,32601143,100210,517.0722,0.9997,0.65
197,61,LKA,Sri Lanka,Colombo,Asia,21832143,21715079,21336697,20668557,18776371,17204094,14943645,12388769,65610,332.7563,1.0027,0.27
202,60,SYR,Syria,Damascus,Asia,22125249,20772595,19205178,22337563,16307654,12408996,8898954,6319199,185180,119.4797,1.0376,0.28
203,57,TWN,Taiwan,Taipei,Asia,23893394,23821464,23512136,23083083,22194731,20586174,18100281,14957870,36193,660.1662,1.0014,0.30
204,95,TJK,Tajikistan,Dushanbe,Asia,9952787,9543207,8524063,7621779,6272998,5417860,4045965,2993019,143100,69.5513,1.0208,0.12
206,20,THA,Thailand,Bangkok,Asia,71697030,71475664,70294397,68270489,63066603,55228410,45737753,35791728,513120,139.7276,1.0013,0.90
207,155,TLS,Timor-Leste,Dili,Asia,1341296,1299995,1205813,1088486,878360,758106,642224,554021,14874,90.1772,1.0154,0.02
213,18,TUR,Turkey,Ankara,Asia,85341241,84135428,79646178,73195345,64113547,54324142,44089069,35540990,783562,108.9145,1.0067,1.07
214,111,TKM,Turkmenistan,Ashgabat,Asia,6430770,6250438,5766431,5267970,4569132,3720278,2862903,2201432,488100,13.1751,1.0140,0.08
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,9441129,9287289,8916899,8481771,3275333,1900151,1014048,298084,83600,112.9322,1.0081,0.12
224,43,UZB,Uzbekistan,Tashkent,Asia,34627652,33526656,30949417,28614227,24925554,20579100,15947129,12011361,447400,77.3975,1.0160,0.43
228,16,VNM,Vietnam,Hanoi,Asia,98186856,96648685,92191398,87411012,79001142,66912613,52968270,41928849,331212,296.4472,1.0074,1.23
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42

#### 3.5 Quyidagi kod World Population Percentage ustunining eng ko'p uchraydigan qiymatini topadi. Natijani mode_value o'zgaruvchisida saqlaydi va ekranga chiqaradi.

In [6]:
mode_value = df['World Population Percentage'].mode()
mode_value

0    0.0
Name: World Population Percentage, dtype: float64

#### 3.6 Quyidagi kod 2022 yildagi eng kam aholi sonini chiqarib beradi.

In [7]:
min_population = df["2022 Population"].min()
min_population

510

#### 3.7 Quyidagi kod 2022 yildagi eng kam aholisi bor davlatni nomini chiqaradi.

In [8]:
df[df["2022 Population"] == min_population]["Country/Territory"].values[0]

'Vatican City'

#### 3.8 Quyidagi kod 2020 yildagi eng ko'p aholi sonini chiqarib beradi.

In [9]:
max_population = df["2020 Population"].max()
max_population

1424929781

#### 3.9 Quyidagi kod 2020 yildagi eng ko'p aholisi bor davlatni nomini chiqaradi.

In [10]:
df[df["2020 Population"] == max_population]["Country/Territory"].values[0]

'China'

#### 3.10 Quyidagi kod 2015 Population ustunining dispersiyasini hisoblab chiqarib beradi.

In [11]:
df["2015 Population"].var()

1.7005462134586562e+16

In [12]:
df[["Area (km²)",]].std()

Area (km²)    1.761841e+06
dtype: float64

#### 3.12 Quyidagi kod 2000 yilda aholi sonini hisoblab beradi.

In [13]:
df["2000 Population"].sum()

6147055703

#### 3.13 Quyidagi kod ustun nomlari, ustunlarning turi, har bir ustundagi qiymatlar soni va xotira hajmi haqida ma'lumot beradi.

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    object
 2   Country/Territory            234 non-null    object
 3   Capital                      234 non-null    object
 4   Continent                    234 non-null    object
 5   2022 Population              234 non-null    int64
 6   2020 Population              234 non-null    int64
 7   2015 Population              234 non-null    int64
 8   2010 Population              234 non-null    int64
 9   2000 Population              234 non-null    int64
 10  1990 Population              234 non-null    int64
 11  1980 Population              234 non-null    int64
 12  1970 Population              234 non-null    int64
 13  Area (km²)                   234 non-null    int64
 14  Density (per km²)            234 non-null    float64
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(3), int64(10), object(4)
memory usage: 31.2+ KB

#### 3.14 Quyidagi kod raqamli ustunlar uchun hisoblaydi soni (count), o'rtacha (mean), standart og'ish (std), minimum (min), 25%, 50%, va 75% kvantillar (25%, 50%, 75%), va maksimum (max) larni

In [15]:
df["Growth Rate"].describe()

count    234.000000
mean       1.009577
std        0.013385
min        0.912000
25%        1.001775
50%        1.007900
75%        1.016950
max        1.069100
Name: Growth Rate, dtype: float64

#### 3.15 Quyidagi kod ustun yoki qatorning unikal qiymatlari va ularga teng bo'lgan qancha marta takrorlanganligini hisoblaydi va natijani Series ko'rinishida qaytaradi.

In [16]:
df["Area (km²)"].value_counts()

Area (km²)
21        2
652230    1
462840    1
923768    1
260       1
         ..
108889    1
78        1
245857    1
36125     1
390757    1
Name: count, Length: 233, dtype: int64

#### Bu kodda groupby() usuli orqali Continent ustuni bo'yicha guruhlash amalga oshiriladi va har bir guruhdagi 2022 Population ustunining o'rtacha qiymati hisoblanadi.

In [17]:
df.groupby('Continent')['2022 Population'].mean()

Continent
Africa           2.503037e+07
Asia             9.442767e+07
Europe           1.486295e+07
North America    1.500740e+07
Oceania          1.958198e+06
South America    3.120119e+07
Name: 2022 Population, dtype: float64

#### Bu kodda, df.sort_index() usuli DataFrame ni avvalgi indeks bo'yicha tartiblaydi

In [18]:
df.sort_index()

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,11655,12182,13142,14723,13454,11315,9377,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,556048,491824,413296,270375,178529,116775,76371,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,32284046,28516545,24743946,18628700,13375121,9204938,6843607,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,18927715,16248230,13792086,9891136,7686401,5720438,4281671,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,15669666,14154937,12839771,11834676,10113893,7049926,5202918,390757,41.7665,1.0204,0.20